DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE PARTICIPANT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTICIPANT VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL
);

CREATE TABLE COUPLE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTNERONE VARCHAR(80) NOT NULL,
    PARTNERTWO VARCHAR(80) NOT NULL
);

CREATE TABLE ASSIGNMENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAMEONE VARCHAR(80) NOT NULL,
    NAMETWO VARCHAR(80) NOT NULL
);